import { PlayerEnum, Score } from "@/models/game.model";

export const SCORE_DATA = <Score[]>[
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 1,
    score: 14,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 2,
    score: 6,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 3,
    score: 56,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 4,
    score: 22,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 5,
    score: 1,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 6,
    score: 10,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 7,
    score: 3,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 1,
    score: 3,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 2,
    score: 39,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 3,
    score: 18,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 4,
    score: 8,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 5,
    score: 11,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 6,
    score: 9,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 7,
    score: 29,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 8,
    score: 14,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 9,
    score: 6,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 10,
    score: 56,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 11,
    score: 22,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 12,
    score: 1,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 13,
    score: 10,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 14,
    score: 3,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 8,
    score: 3,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 9,
    score: 39,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 10,
    score: 18,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 11,
    score: 8,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 12,
    score: 11,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 13,
    score: 9,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 14,
    score: 29,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 15,
    score: 14,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 16,
    score: 6,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 17,
    score: 56,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 18,
    score: 22,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 19,
    score: 1,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 20,
    score: 10,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 21,
    score: 3,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 15,
    score: 3,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 16,
    score: 39,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 17,
    score: 18,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 18,
    score: 8,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 19,
    score: 11,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 20,
    score: 9,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 21,
    score: 29,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 22,
    score: 14,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 23,
    score: 6,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 24,
    score: 56,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 25,
    score: 22,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 26,
    score: 1,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 27,
    score: 10,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_ONE,
    inning: 28,
    score: 3,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 22,
    score: 3,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 23,
    score: 39,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 24,
    score: 18,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 25,
    score: 8,
    foul: true,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 26,
    score: 11,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 27,
    score: 9,
    foul: false,
  },
  {
    player: PlayerEnum.PLAYER_TWO,
    inning: 28,
    score: 29,
    foul: false,
  },
];
